INFO_CURRENT_LEVEL_TEXT = "Level "

GAME_OVER_MENU_MAIN_TEXT = "Game Over"
GAME_OVER_MENU_INFO_TEXT = "Levels Completed: "
GAME_OVER_MENU_PLAY_AGAIN_TEXT = "Play Again"
GAME_OVER_MENU_QUIT_TEXT = "Quit"

HOME_MENU_PLAY_TEXT = "Play"
HOME_MENU_QUIT_TEXT = "Quit"