WIDTH = 800
HEIGHT = 800
FPS = 60

TILESIZE = 16
ZOOM = 2
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

LEVEL_INFO_PANEL_POSITION = (20, 20)
MAIN_INFO_PANEL_POSITION = (WIDTH / 2 - 80, HEIGHT - 20)
